// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/equipment/equipment.proto

package protoEquipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomeRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeName      string                 `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRP) Reset() {
	*x = HomeRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRP) ProtoMessage() {}

func (x *HomeRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRP.ProtoReflect.Descriptor instead.
func (*HomeRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *HomeRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomeRP) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *HomeRP) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *HomeRP) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *HomeRP) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AreaRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRP) Reset() {
	*x = AreaRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRP) ProtoMessage() {}

func (x *AreaRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRP.ProtoReflect.Descriptor instead.
func (*AreaRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *AreaRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AreaRP) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *AreaRP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EquipmentRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	HomeId        int32                  `protobuf:"varint,3,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TimeStart     string                 `protobuf:"bytes,6,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,7,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	TurnOn        bool                   `protobuf:"varint,8,opt,name=turnOn,proto3" json:"turnOn,omitempty"`
	Cycle         int32                  `protobuf:"varint,9,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRP) Reset() {
	*x = EquipmentRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRP) ProtoMessage() {}

func (x *EquipmentRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRP.ProtoReflect.Descriptor instead.
func (*EquipmentRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentRP) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *EquipmentRP) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *EquipmentRP) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EquipmentRP) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EquipmentRP) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *EquipmentRP) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *EquipmentRP) GetTurnOn() bool {
	if x != nil {
		return x.TurnOn
	}
	return false
}

func (x *EquipmentRP) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *EquipmentRP) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRQ) Reset() {
	*x = EquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRQ) ProtoMessage() {}

func (x *EquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRQ.ProtoReflect.Descriptor instead.
func (*EquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *EquipmentRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

type HomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRQ) Reset() {
	*x = HomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRQ) ProtoMessage() {}

func (x *HomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRQ.ProtoReflect.Descriptor instead.
func (*HomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{4}
}

func (x *HomeRQ) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type AreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRQ) Reset() {
	*x = AreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRQ) ProtoMessage() {}

func (x *AreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRQ.ProtoReflect.Descriptor instead.
func (*AreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{5}
}

func (x *AreaRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

type ListHomeRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Homes         []*HomeRP              `protobuf:"bytes,1,rep,name=homes,proto3" json:"homes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHomeRP) Reset() {
	*x = ListHomeRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHomeRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeRP) ProtoMessage() {}

func (x *ListHomeRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeRP.ProtoReflect.Descriptor instead.
func (*ListHomeRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{6}
}

func (x *ListHomeRP) GetHomes() []*HomeRP {
	if x != nil {
		return x.Homes
	}
	return nil
}

type ListAreaRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*AreaRP              `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreaRP) Reset() {
	*x = ListAreaRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreaRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaRP) ProtoMessage() {}

func (x *ListAreaRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaRP.ProtoReflect.Descriptor instead.
func (*ListAreaRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{7}
}

func (x *ListAreaRP) GetAreas() []*AreaRP {
	if x != nil {
		return x.Areas
	}
	return nil
}

type ListEquimentRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equipments    []*EquipmentRP         `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEquimentRP) Reset() {
	*x = ListEquimentRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEquimentRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEquimentRP) ProtoMessage() {}

func (x *ListEquimentRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEquimentRP.ProtoReflect.Descriptor instead.
func (*ListEquimentRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{8}
}

func (x *ListEquimentRP) GetEquipments() []*EquipmentRP {
	if x != nil {
		return x.Equipments
	}
	return nil
}

type CreateHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	HomeName      string                 `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomeRQ) Reset() {
	*x = CreateHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomeRQ) ProtoMessage() {}

func (x *CreateHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomeRQ.ProtoReflect.Descriptor instead.
func (*CreateHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{9}
}

func (x *CreateHomeRQ) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateHomeRQ) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *CreateHomeRQ) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateHomeRQ) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *CreateHomeRQ) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHomeRQ) Reset() {
	*x = DeleteHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHomeRQ) ProtoMessage() {}

func (x *DeleteHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHomeRQ.ProtoReflect.Descriptor instead.
func (*DeleteHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHomeRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditHomeRQ) Reset() {
	*x = EditHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditHomeRQ) ProtoMessage() {}

func (x *EditHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditHomeRQ.ProtoReflect.Descriptor instead.
func (*EditHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{11}
}

func (x *EditHomeRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAreaRQ) Reset() {
	*x = CreateAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaRQ) ProtoMessage() {}

func (x *CreateAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaRQ.ProtoReflect.Descriptor instead.
func (*CreateAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{12}
}

func (x *CreateAreaRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *CreateAreaRQ) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAreaRQ) Reset() {
	*x = DeleteAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaRQ) ProtoMessage() {}

func (x *DeleteAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaRQ.ProtoReflect.Descriptor instead.
func (*DeleteAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAreaRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAreaRQ) Reset() {
	*x = EditAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAreaRQ) ProtoMessage() {}

func (x *EditAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAreaRQ.ProtoReflect.Descriptor instead.
func (*EditAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{14}
}

func (x *EditAreaRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TimeStart     string                 `protobuf:"bytes,5,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,6,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	Cycle         int32                  `protobuf:"varint,8,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEquipmentRQ) Reset() {
	*x = CreateEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEquipmentRQ) ProtoMessage() {}

func (x *CreateEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEquipmentRQ.ProtoReflect.Descriptor instead.
func (*CreateEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{15}
}

func (x *CreateEquipmentRQ) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateEquipmentRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *CreateEquipmentRQ) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEquipmentRQ) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEquipmentRQ) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *CreateEquipmentRQ) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *CreateEquipmentRQ) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *CreateEquipmentRQ) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEquipmentRQ) Reset() {
	*x = DeleteEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEquipmentRQ) ProtoMessage() {}

func (x *DeleteEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEquipmentRQ.ProtoReflect.Descriptor instead.
func (*DeleteEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteEquipmentRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEquipmentRQ) Reset() {
	*x = EditEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEquipmentRQ) ProtoMessage() {}

func (x *EditEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEquipmentRQ.ProtoReflect.Descriptor instead.
func (*EditEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{17}
}

func (x *EditEquipmentRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SuccessRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessRP) Reset() {
	*x = SuccessRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessRP) ProtoMessage() {}

func (x *SuccessRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessRP.ProtoReflect.Descriptor instead.
func (*SuccessRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{18}
}

func (x *SuccessRP) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SuccessRP) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_equipment_equipment_proto protoreflect.FileDescriptor

var file_proto_equipment_equipment_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a,
	0x06, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x44, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8b, 0x02,
	0x0a, 0x0b, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f,
	0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x26, 0x0a, 0x06, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x51, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x51, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x12, 0x27, 0x0a, 0x05, 0x68, 0x6f,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x52, 0x05, 0x68, 0x6f,
	0x6d, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x50, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x50, 0x52, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x22, 0x48, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x71, 0x75, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x12, 0x36, 0x0a, 0x0a,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48,
	0x6f, 0x6d, 0x65, 0x52, 0x51, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x6d,
	0x65, 0x52, 0x51, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x0a, 0x45, 0x64, 0x69, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x52,
	0x51, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x51, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x51, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a,
	0x0a, 0x45, 0x64, 0x69, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x51, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xe9, 0x01, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x51, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f,
	0x45, 0x64, 0x69, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x31, 0x0a, 0x09, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x50, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0xfd, 0x05, 0x0a, 0x10, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x12,
	0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x6d, 0x65,
	0x52, 0x51, 0x1a, 0x15, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65,
	0x52, 0x51, 0x1a, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x52, 0x50, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x51, 0x1a, 0x14,
	0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x50, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x12, 0x15, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x64, 0x69, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x51, 0x1a, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x22, 0x00, 0x12, 0x32,
	0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x51, 0x1a, 0x15, 0x2e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x50,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x17, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x51, 0x1a, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x50, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x12, 0x17, 0x2e, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x51, 0x1a, 0x14, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x50, 0x22, 0x00, 0x12, 0x36, 0x0a,
	0x08, 0x45, 0x64, 0x69, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x15, 0x2e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x51,
	0x1a, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x50, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x1a, 0x19, 0x2e, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x71, 0x75, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x50, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x1a, 0x16, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x51, 0x1a, 0x14, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x50, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0d, 0x45,
	0x64, 0x69, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x1a, 0x16, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50,
	0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_equipment_equipment_proto_rawDescOnce sync.Once
	file_proto_equipment_equipment_proto_rawDescData []byte
)

func file_proto_equipment_equipment_proto_rawDescGZIP() []byte {
	file_proto_equipment_equipment_proto_rawDescOnce.Do(func() {
		file_proto_equipment_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_equipment_equipment_proto_rawDesc), len(file_proto_equipment_equipment_proto_rawDesc)))
	})
	return file_proto_equipment_equipment_proto_rawDescData
}

var file_proto_equipment_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_equipment_equipment_proto_goTypes = []any{
	(*HomeRP)(nil),            // 0: equipment.HomeRP
	(*AreaRP)(nil),            // 1: equipment.AreaRP
	(*EquipmentRP)(nil),       // 2: equipment.EquipmentRP
	(*EquipmentRQ)(nil),       // 3: equipment.EquipmentRQ
	(*HomeRQ)(nil),            // 4: equipment.HomeRQ
	(*AreaRQ)(nil),            // 5: equipment.AreaRQ
	(*ListHomeRP)(nil),        // 6: equipment.ListHomeRP
	(*ListAreaRP)(nil),        // 7: equipment.ListAreaRP
	(*ListEquimentRP)(nil),    // 8: equipment.ListEquimentRP
	(*CreateHomeRQ)(nil),      // 9: equipment.CreateHomeRQ
	(*DeleteHomeRQ)(nil),      // 10: equipment.DeleteHomeRQ
	(*EditHomeRQ)(nil),        // 11: equipment.EditHomeRQ
	(*CreateAreaRQ)(nil),      // 12: equipment.CreateAreaRQ
	(*DeleteAreaRQ)(nil),      // 13: equipment.DeleteAreaRQ
	(*EditAreaRQ)(nil),        // 14: equipment.EditAreaRQ
	(*CreateEquipmentRQ)(nil), // 15: equipment.CreateEquipmentRQ
	(*DeleteEquipmentRQ)(nil), // 16: equipment.DeleteEquipmentRQ
	(*EditEquipmentRQ)(nil),   // 17: equipment.EditEquipmentRQ
	(*SuccessRP)(nil),         // 18: equipment.SuccessRP
}
var file_proto_equipment_equipment_proto_depIdxs = []int32{
	0,  // 0: equipment.ListHomeRP.homes:type_name -> equipment.HomeRP
	1,  // 1: equipment.ListAreaRP.areas:type_name -> equipment.AreaRP
	2,  // 2: equipment.ListEquimentRP.equipments:type_name -> equipment.EquipmentRP
	4,  // 3: equipment.EquipmentService.Home:input_type -> equipment.HomeRQ
	9,  // 4: equipment.EquipmentService.CreateHome:input_type -> equipment.CreateHomeRQ
	10, // 5: equipment.EquipmentService.DeleteHome:input_type -> equipment.DeleteHomeRQ
	11, // 6: equipment.EquipmentService.EditHome:input_type -> equipment.EditHomeRQ
	5,  // 7: equipment.EquipmentService.Area:input_type -> equipment.AreaRQ
	12, // 8: equipment.EquipmentService.CreateArea:input_type -> equipment.CreateAreaRQ
	13, // 9: equipment.EquipmentService.DeleteArea:input_type -> equipment.DeleteAreaRQ
	14, // 10: equipment.EquipmentService.EditArea:input_type -> equipment.EditAreaRQ
	3,  // 11: equipment.EquipmentService.Equipment:input_type -> equipment.EquipmentRQ
	15, // 12: equipment.EquipmentService.CreateEquipment:input_type -> equipment.CreateEquipmentRQ
	16, // 13: equipment.EquipmentService.DeleteEquipment:input_type -> equipment.DeleteEquipmentRQ
	17, // 14: equipment.EquipmentService.EditEquipment:input_type -> equipment.EditEquipmentRQ
	6,  // 15: equipment.EquipmentService.Home:output_type -> equipment.ListHomeRP
	0,  // 16: equipment.EquipmentService.CreateHome:output_type -> equipment.HomeRP
	18, // 17: equipment.EquipmentService.DeleteHome:output_type -> equipment.SuccessRP
	0,  // 18: equipment.EquipmentService.EditHome:output_type -> equipment.HomeRP
	7,  // 19: equipment.EquipmentService.Area:output_type -> equipment.ListAreaRP
	1,  // 20: equipment.EquipmentService.CreateArea:output_type -> equipment.AreaRP
	18, // 21: equipment.EquipmentService.DeleteArea:output_type -> equipment.SuccessRP
	1,  // 22: equipment.EquipmentService.EditArea:output_type -> equipment.AreaRP
	8,  // 23: equipment.EquipmentService.Equipment:output_type -> equipment.ListEquimentRP
	2,  // 24: equipment.EquipmentService.CreateEquipment:output_type -> equipment.EquipmentRP
	18, // 25: equipment.EquipmentService.DeleteEquipment:output_type -> equipment.SuccessRP
	2,  // 26: equipment.EquipmentService.EditEquipment:output_type -> equipment.EquipmentRP
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_equipment_equipment_proto_init() }
func file_proto_equipment_equipment_proto_init() {
	if File_proto_equipment_equipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_equipment_equipment_proto_rawDesc), len(file_proto_equipment_equipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_equipment_equipment_proto_goTypes,
		DependencyIndexes: file_proto_equipment_equipment_proto_depIdxs,
		MessageInfos:      file_proto_equipment_equipment_proto_msgTypes,
	}.Build()
	File_proto_equipment_equipment_proto = out.File
	file_proto_equipment_equipment_proto_goTypes = nil
	file_proto_equipment_equipment_proto_depIdxs = nil
}
