// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/equipment/equipment.proto

package protoEquipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomeRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeName      string                 `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRP) Reset() {
	*x = HomeRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRP) ProtoMessage() {}

func (x *HomeRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRP.ProtoReflect.Descriptor instead.
func (*HomeRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *HomeRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomeRP) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *HomeRP) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *HomeRP) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *HomeRP) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AreaRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRP) Reset() {
	*x = AreaRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRP) ProtoMessage() {}

func (x *AreaRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRP.ProtoReflect.Descriptor instead.
func (*AreaRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *AreaRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AreaRP) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *AreaRP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EquipmentRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	HomeId        int32                  `protobuf:"varint,3,opt,name=homeId,proto3" json:"homeId,omitempty"`
	AreaId        int32                  `protobuf:"varint,4,opt,name=areaId,proto3" json:"areaId,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	TimeStart     string                 `protobuf:"bytes,7,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,8,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	TurnOn        bool                   `protobuf:"varint,9,opt,name=turnOn,proto3" json:"turnOn,omitempty"`
	Cycle         int32                  `protobuf:"varint,10,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRP) Reset() {
	*x = EquipmentRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRP) ProtoMessage() {}

func (x *EquipmentRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRP.ProtoReflect.Descriptor instead.
func (*EquipmentRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentRP) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *EquipmentRP) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *EquipmentRP) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *EquipmentRP) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EquipmentRP) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EquipmentRP) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *EquipmentRP) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *EquipmentRP) GetTurnOn() bool {
	if x != nil {
		return x.TurnOn
	}
	return false
}

func (x *EquipmentRP) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *EquipmentRP) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        int32                  `protobuf:"varint,1,opt,name=areaId,proto3" json:"areaId,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRQ) Reset() {
	*x = EquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRQ) ProtoMessage() {}

func (x *EquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRQ.ProtoReflect.Descriptor instead.
func (*EquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *EquipmentRQ) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *EquipmentRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

type HomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRQ) Reset() {
	*x = HomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRQ) ProtoMessage() {}

func (x *HomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRQ.ProtoReflect.Descriptor instead.
func (*HomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{4}
}

func (x *HomeRQ) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type AreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRQ) Reset() {
	*x = AreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRQ) ProtoMessage() {}

func (x *AreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRQ.ProtoReflect.Descriptor instead.
func (*AreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{5}
}

func (x *AreaRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

type ListHomeRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Homes         []*HomeRP              `protobuf:"bytes,1,rep,name=homes,proto3" json:"homes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHomeRP) Reset() {
	*x = ListHomeRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHomeRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeRP) ProtoMessage() {}

func (x *ListHomeRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeRP.ProtoReflect.Descriptor instead.
func (*ListHomeRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{6}
}

func (x *ListHomeRP) GetHomes() []*HomeRP {
	if x != nil {
		return x.Homes
	}
	return nil
}

type ListAreaRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*AreaRP              `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreaRP) Reset() {
	*x = ListAreaRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreaRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaRP) ProtoMessage() {}

func (x *ListAreaRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaRP.ProtoReflect.Descriptor instead.
func (*ListAreaRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{7}
}

func (x *ListAreaRP) GetAreas() []*AreaRP {
	if x != nil {
		return x.Areas
	}
	return nil
}

type ListEquimentRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equipments    []*EquipmentRP         `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEquimentRP) Reset() {
	*x = ListEquimentRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEquimentRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEquimentRP) ProtoMessage() {}

func (x *ListEquimentRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEquimentRP.ProtoReflect.Descriptor instead.
func (*ListEquimentRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{8}
}

func (x *ListEquimentRP) GetEquipments() []*EquipmentRP {
	if x != nil {
		return x.Equipments
	}
	return nil
}

type CreateHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	HomeName      string                 `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomeRQ) Reset() {
	*x = CreateHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomeRQ) ProtoMessage() {}

func (x *CreateHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomeRQ.ProtoReflect.Descriptor instead.
func (*CreateHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{9}
}

func (x *CreateHomeRQ) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateHomeRQ) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *CreateHomeRQ) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateHomeRQ) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *CreateHomeRQ) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHomeRQ) Reset() {
	*x = DeleteHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHomeRQ) ProtoMessage() {}

func (x *DeleteHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHomeRQ.ProtoReflect.Descriptor instead.
func (*DeleteHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHomeRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeName      string                 `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditHomeRQ) Reset() {
	*x = EditHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditHomeRQ) ProtoMessage() {}

func (x *EditHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditHomeRQ.ProtoReflect.Descriptor instead.
func (*EditHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{11}
}

func (x *EditHomeRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditHomeRQ) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *EditHomeRQ) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EditHomeRQ) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type CreateAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAreaRQ) Reset() {
	*x = CreateAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaRQ) ProtoMessage() {}

func (x *CreateAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaRQ.ProtoReflect.Descriptor instead.
func (*CreateAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{12}
}

func (x *CreateAreaRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *CreateAreaRQ) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAreaRQ) Reset() {
	*x = DeleteAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaRQ) ProtoMessage() {}

func (x *DeleteAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaRQ.ProtoReflect.Descriptor instead.
func (*DeleteAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAreaRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAreaRQ) Reset() {
	*x = EditAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAreaRQ) ProtoMessage() {}

func (x *EditAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAreaRQ.ProtoReflect.Descriptor instead.
func (*EditAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{14}
}

func (x *EditAreaRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditAreaRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *EditAreaRQ) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	AreaId        int32                  `protobuf:"varint,3,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TimeStart     string                 `protobuf:"bytes,6,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,7,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	Cycle         int32                  `protobuf:"varint,8,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEquipmentRQ) Reset() {
	*x = CreateEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEquipmentRQ) ProtoMessage() {}

func (x *CreateEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEquipmentRQ.ProtoReflect.Descriptor instead.
func (*CreateEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{15}
}

func (x *CreateEquipmentRQ) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateEquipmentRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *CreateEquipmentRQ) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *CreateEquipmentRQ) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEquipmentRQ) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEquipmentRQ) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *CreateEquipmentRQ) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *CreateEquipmentRQ) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *CreateEquipmentRQ) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEquipmentRQ) Reset() {
	*x = DeleteEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEquipmentRQ) ProtoMessage() {}

func (x *DeleteEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEquipmentRQ.ProtoReflect.Descriptor instead.
func (*DeleteEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteEquipmentRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	HomeId        int32                  `protobuf:"varint,3,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEquipmentRQ) Reset() {
	*x = EditEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEquipmentRQ) ProtoMessage() {}

func (x *EditEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEquipmentRQ.ProtoReflect.Descriptor instead.
func (*EditEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{17}
}

func (x *EditEquipmentRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditEquipmentRQ) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *EditEquipmentRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *EditEquipmentRQ) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditEquipmentRQ) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SuccessRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessRP) Reset() {
	*x = SuccessRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessRP) ProtoMessage() {}

func (x *SuccessRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessRP.ProtoReflect.Descriptor instead.
func (*SuccessRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{18}
}

func (x *SuccessRP) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SuccessRP) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CheckHomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHomeRQ) Reset() {
	*x = CheckHomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHomeRQ) ProtoMessage() {}

func (x *CheckHomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHomeRQ.ProtoReflect.Descriptor instead.
func (*CheckHomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{19}
}

func (x *CheckHomeRQ) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CheckHomeRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckAreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAreaRQ) Reset() {
	*x = CheckAreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAreaRQ) ProtoMessage() {}

func (x *CheckAreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAreaRQ.ProtoReflect.Descriptor instead.
func (*CheckAreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{20}
}

func (x *CheckAreaRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEquipmentRQ) Reset() {
	*x = CheckEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEquipmentRQ) ProtoMessage() {}

func (x *CheckEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEquipmentRQ.ProtoReflect.Descriptor instead.
func (*CheckEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{21}
}

func (x *CheckEquipmentRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChangeEquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TurnOn        bool                   `protobuf:"varint,2,opt,name=turnOn,proto3" json:"turnOn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEquipmentRQ) Reset() {
	*x = ChangeEquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEquipmentRQ) ProtoMessage() {}

func (x *ChangeEquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEquipmentRQ.ProtoReflect.Descriptor instead.
func (*ChangeEquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{22}
}

func (x *ChangeEquipmentRQ) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeEquipmentRQ) GetTurnOn() bool {
	if x != nil {
		return x.TurnOn
	}
	return false
}

type ChangeEquipmentTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeStart     string                 `protobuf:"bytes,2,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,3,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEquipmentTime) Reset() {
	*x = ChangeEquipmentTime{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEquipmentTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEquipmentTime) ProtoMessage() {}

func (x *ChangeEquipmentTime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEquipmentTime.ProtoReflect.Descriptor instead.
func (*ChangeEquipmentTime) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{23}
}

func (x *ChangeEquipmentTime) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeEquipmentTime) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *ChangeEquipmentTime) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

var File_proto_equipment_equipment_proto protoreflect.FileDescriptor

const file_proto_equipment_equipment_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/equipment/equipment.proto\x12\tequipment\"\x88\x01\n" +
	"\x06HomeRP\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bhomeName\x18\x02 \x01(\tR\bhomeName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\"D\n" +
	"\x06AreaRP\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06homeId\x18\x02 \x01(\x05R\x06homeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa3\x02\n" +
	"\vEquipmentRP\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x16\n" +
	"\x06homeId\x18\x03 \x01(\x05R\x06homeId\x12\x16\n" +
	"\x06areaId\x18\x04 \x01(\x05R\x06areaId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimeStart\x18\a \x01(\tR\ttimeStart\x12\x18\n" +
	"\atimeEnd\x18\b \x01(\tR\atimeEnd\x12\x16\n" +
	"\x06turnOn\x18\t \x01(\bR\x06turnOn\x12\x14\n" +
	"\x05cycle\x18\n" +
	" \x01(\x05R\x05cycle\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"=\n" +
	"\vEquipmentRQ\x12\x16\n" +
	"\x06areaId\x18\x01 \x01(\x05R\x06areaId\x12\x16\n" +
	"\x06homeId\x18\x02 \x01(\x05R\x06homeId\"&\n" +
	"\x06HomeRQ\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x05R\taccountId\" \n" +
	"\x06AreaRQ\x12\x16\n" +
	"\x06homeId\x18\x01 \x01(\x05R\x06homeId\"5\n" +
	"\n" +
	"ListHomeRP\x12'\n" +
	"\x05homes\x18\x01 \x03(\v2\x11.equipment.HomeRPR\x05homes\"5\n" +
	"\n" +
	"ListAreaRP\x12'\n" +
	"\x05areas\x18\x01 \x03(\v2\x11.equipment.AreaRPR\x05areas\"H\n" +
	"\x0eListEquimentRP\x126\n" +
	"\n" +
	"equipments\x18\x01 \x03(\v2\x16.equipment.EquipmentRPR\n" +
	"equipments\"\x9c\x01\n" +
	"\fCreateHomeRQ\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x05R\taccountId\x12\x1a\n" +
	"\bhomeName\x18\x02 \x01(\tR\bhomeName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\"\x1e\n" +
	"\fDeleteHomeRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"n\n" +
	"\n" +
	"EditHomeRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bhomeName\x18\x02 \x01(\tR\bhomeName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\":\n" +
	"\fCreateAreaRQ\x12\x16\n" +
	"\x06homeId\x18\x01 \x01(\x05R\x06homeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1e\n" +
	"\fDeleteAreaRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"H\n" +
	"\n" +
	"EditAreaRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06homeId\x18\x02 \x01(\x05R\x06homeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x81\x02\n" +
	"\x11CreateEquipmentRQ\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x16\n" +
	"\x06homeId\x18\x02 \x01(\x05R\x06homeId\x12\x16\n" +
	"\x06AreaId\x18\x03 \x01(\x05R\x06AreaId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimeStart\x18\x06 \x01(\tR\ttimeStart\x12\x18\n" +
	"\atimeEnd\x18\a \x01(\tR\atimeEnd\x12\x14\n" +
	"\x05cycle\x18\b \x01(\x05R\x05cycle\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"#\n" +
	"\x11DeleteEquipmentRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x91\x01\n" +
	"\x0fEditEquipmentRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x16\n" +
	"\x06homeId\x18\x03 \x01(\x05R\x06homeId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"1\n" +
	"\tSuccessRP\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\";\n" +
	"\vCheckHomeRQ\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x05R\taccountId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\x1d\n" +
	"\vCheckAreaRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\"\n" +
	"\x10checkEquipmentRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\";\n" +
	"\x11ChangeEquipmentRQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06turnOn\x18\x02 \x01(\bR\x06turnOn\"]\n" +
	"\x13ChangeEquipmentTime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\ttimeStart\x18\x02 \x01(\tR\ttimeStart\x12\x18\n" +
	"\atimeEnd\x18\x03 \x01(\tR\atimeEnd2\xc6\b\n" +
	"\x10EquipmentService\x122\n" +
	"\x04Home\x12\x11.equipment.HomeRQ\x1a\x15.equipment.ListHomeRP\"\x00\x12:\n" +
	"\n" +
	"CreateHome\x12\x17.equipment.CreateHomeRQ\x1a\x11.equipment.HomeRP\"\x00\x12=\n" +
	"\n" +
	"DeleteHome\x12\x17.equipment.DeleteHomeRQ\x1a\x14.equipment.SuccessRP\"\x00\x126\n" +
	"\bEditHome\x12\x15.equipment.EditHomeRQ\x1a\x11.equipment.HomeRP\"\x00\x128\n" +
	"\tCheckHome\x12\x16.equipment.CheckHomeRQ\x1a\x11.equipment.HomeRP\"\x00\x122\n" +
	"\x04Area\x12\x11.equipment.AreaRQ\x1a\x15.equipment.ListAreaRP\"\x00\x12:\n" +
	"\n" +
	"CreateArea\x12\x17.equipment.CreateAreaRQ\x1a\x11.equipment.AreaRP\"\x00\x12=\n" +
	"\n" +
	"DeleteArea\x12\x17.equipment.DeleteAreaRQ\x1a\x14.equipment.SuccessRP\"\x00\x126\n" +
	"\bEditArea\x12\x15.equipment.EditAreaRQ\x1a\x11.equipment.AreaRP\"\x00\x128\n" +
	"\tCheckArea\x12\x16.equipment.CheckAreaRQ\x1a\x11.equipment.AreaRP\"\x00\x12@\n" +
	"\tEquipment\x12\x16.equipment.EquipmentRQ\x1a\x19.equipment.ListEquimentRP\"\x00\x12I\n" +
	"\x0fCreateEquipment\x12\x1c.equipment.CreateEquipmentRQ\x1a\x16.equipment.EquipmentRP\"\x00\x12G\n" +
	"\x0fDeleteEquipment\x12\x1c.equipment.DeleteEquipmentRQ\x1a\x14.equipment.SuccessRP\"\x00\x12E\n" +
	"\rEditEquipment\x12\x1a.equipment.EditEquipmentRQ\x1a\x16.equipment.EquipmentRP\"\x00\x12G\n" +
	"\x0eCheckEquipment\x12\x1b.equipment.checkEquipmentRQ\x1a\x16.equipment.EquipmentRP\"\x00\x12D\n" +
	"\fChangeTurnOn\x12\x1c.equipment.ChangeEquipmentRQ\x1a\x14.equipment.SuccessRP\"\x00\x12D\n" +
	"\n" +
	"ChangeTime\x12\x1e.equipment.ChangeEquipmentTime\x1a\x14.equipment.SuccessRP\"\x00B\x1bZ\x19github.com/protoEquipmentb\x06proto3"

var (
	file_proto_equipment_equipment_proto_rawDescOnce sync.Once
	file_proto_equipment_equipment_proto_rawDescData []byte
)

func file_proto_equipment_equipment_proto_rawDescGZIP() []byte {
	file_proto_equipment_equipment_proto_rawDescOnce.Do(func() {
		file_proto_equipment_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_equipment_equipment_proto_rawDesc), len(file_proto_equipment_equipment_proto_rawDesc)))
	})
	return file_proto_equipment_equipment_proto_rawDescData
}

var file_proto_equipment_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_equipment_equipment_proto_goTypes = []any{
	(*HomeRP)(nil),              // 0: equipment.HomeRP
	(*AreaRP)(nil),              // 1: equipment.AreaRP
	(*EquipmentRP)(nil),         // 2: equipment.EquipmentRP
	(*EquipmentRQ)(nil),         // 3: equipment.EquipmentRQ
	(*HomeRQ)(nil),              // 4: equipment.HomeRQ
	(*AreaRQ)(nil),              // 5: equipment.AreaRQ
	(*ListHomeRP)(nil),          // 6: equipment.ListHomeRP
	(*ListAreaRP)(nil),          // 7: equipment.ListAreaRP
	(*ListEquimentRP)(nil),      // 8: equipment.ListEquimentRP
	(*CreateHomeRQ)(nil),        // 9: equipment.CreateHomeRQ
	(*DeleteHomeRQ)(nil),        // 10: equipment.DeleteHomeRQ
	(*EditHomeRQ)(nil),          // 11: equipment.EditHomeRQ
	(*CreateAreaRQ)(nil),        // 12: equipment.CreateAreaRQ
	(*DeleteAreaRQ)(nil),        // 13: equipment.DeleteAreaRQ
	(*EditAreaRQ)(nil),          // 14: equipment.EditAreaRQ
	(*CreateEquipmentRQ)(nil),   // 15: equipment.CreateEquipmentRQ
	(*DeleteEquipmentRQ)(nil),   // 16: equipment.DeleteEquipmentRQ
	(*EditEquipmentRQ)(nil),     // 17: equipment.EditEquipmentRQ
	(*SuccessRP)(nil),           // 18: equipment.SuccessRP
	(*CheckHomeRQ)(nil),         // 19: equipment.CheckHomeRQ
	(*CheckAreaRQ)(nil),         // 20: equipment.CheckAreaRQ
	(*CheckEquipmentRQ)(nil),    // 21: equipment.checkEquipmentRQ
	(*ChangeEquipmentRQ)(nil),   // 22: equipment.ChangeEquipmentRQ
	(*ChangeEquipmentTime)(nil), // 23: equipment.ChangeEquipmentTime
}
var file_proto_equipment_equipment_proto_depIdxs = []int32{
	0,  // 0: equipment.ListHomeRP.homes:type_name -> equipment.HomeRP
	1,  // 1: equipment.ListAreaRP.areas:type_name -> equipment.AreaRP
	2,  // 2: equipment.ListEquimentRP.equipments:type_name -> equipment.EquipmentRP
	4,  // 3: equipment.EquipmentService.Home:input_type -> equipment.HomeRQ
	9,  // 4: equipment.EquipmentService.CreateHome:input_type -> equipment.CreateHomeRQ
	10, // 5: equipment.EquipmentService.DeleteHome:input_type -> equipment.DeleteHomeRQ
	11, // 6: equipment.EquipmentService.EditHome:input_type -> equipment.EditHomeRQ
	19, // 7: equipment.EquipmentService.CheckHome:input_type -> equipment.CheckHomeRQ
	5,  // 8: equipment.EquipmentService.Area:input_type -> equipment.AreaRQ
	12, // 9: equipment.EquipmentService.CreateArea:input_type -> equipment.CreateAreaRQ
	13, // 10: equipment.EquipmentService.DeleteArea:input_type -> equipment.DeleteAreaRQ
	14, // 11: equipment.EquipmentService.EditArea:input_type -> equipment.EditAreaRQ
	20, // 12: equipment.EquipmentService.CheckArea:input_type -> equipment.CheckAreaRQ
	3,  // 13: equipment.EquipmentService.Equipment:input_type -> equipment.EquipmentRQ
	15, // 14: equipment.EquipmentService.CreateEquipment:input_type -> equipment.CreateEquipmentRQ
	16, // 15: equipment.EquipmentService.DeleteEquipment:input_type -> equipment.DeleteEquipmentRQ
	17, // 16: equipment.EquipmentService.EditEquipment:input_type -> equipment.EditEquipmentRQ
	21, // 17: equipment.EquipmentService.CheckEquipment:input_type -> equipment.checkEquipmentRQ
	22, // 18: equipment.EquipmentService.ChangeTurnOn:input_type -> equipment.ChangeEquipmentRQ
	23, // 19: equipment.EquipmentService.ChangeTime:input_type -> equipment.ChangeEquipmentTime
	6,  // 20: equipment.EquipmentService.Home:output_type -> equipment.ListHomeRP
	0,  // 21: equipment.EquipmentService.CreateHome:output_type -> equipment.HomeRP
	18, // 22: equipment.EquipmentService.DeleteHome:output_type -> equipment.SuccessRP
	0,  // 23: equipment.EquipmentService.EditHome:output_type -> equipment.HomeRP
	0,  // 24: equipment.EquipmentService.CheckHome:output_type -> equipment.HomeRP
	7,  // 25: equipment.EquipmentService.Area:output_type -> equipment.ListAreaRP
	1,  // 26: equipment.EquipmentService.CreateArea:output_type -> equipment.AreaRP
	18, // 27: equipment.EquipmentService.DeleteArea:output_type -> equipment.SuccessRP
	1,  // 28: equipment.EquipmentService.EditArea:output_type -> equipment.AreaRP
	1,  // 29: equipment.EquipmentService.CheckArea:output_type -> equipment.AreaRP
	8,  // 30: equipment.EquipmentService.Equipment:output_type -> equipment.ListEquimentRP
	2,  // 31: equipment.EquipmentService.CreateEquipment:output_type -> equipment.EquipmentRP
	18, // 32: equipment.EquipmentService.DeleteEquipment:output_type -> equipment.SuccessRP
	2,  // 33: equipment.EquipmentService.EditEquipment:output_type -> equipment.EquipmentRP
	2,  // 34: equipment.EquipmentService.CheckEquipment:output_type -> equipment.EquipmentRP
	18, // 35: equipment.EquipmentService.ChangeTurnOn:output_type -> equipment.SuccessRP
	18, // 36: equipment.EquipmentService.ChangeTime:output_type -> equipment.SuccessRP
	20, // [20:37] is the sub-list for method output_type
	3,  // [3:20] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_equipment_equipment_proto_init() }
func file_proto_equipment_equipment_proto_init() {
	if File_proto_equipment_equipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_equipment_equipment_proto_rawDesc), len(file_proto_equipment_equipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_equipment_equipment_proto_goTypes,
		DependencyIndexes: file_proto_equipment_equipment_proto_depIdxs,
		MessageInfos:      file_proto_equipment_equipment_proto_msgTypes,
	}.Build()
	File_proto_equipment_equipment_proto = out.File
	file_proto_equipment_equipment_proto_goTypes = nil
	file_proto_equipment_equipment_proto_depIdxs = nil
}
