// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/equipment/equipment.proto

package protoEquipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomeRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeName      string                 `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreateAt      string                 `protobuf:"bytes,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRP) Reset() {
	*x = HomeRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRP) ProtoMessage() {}

func (x *HomeRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRP.ProtoReflect.Descriptor instead.
func (*HomeRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *HomeRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomeRP) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *HomeRP) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *HomeRP) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *HomeRP) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type AreaRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HomeId        int32                  `protobuf:"varint,2,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRP) Reset() {
	*x = AreaRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRP) ProtoMessage() {}

func (x *AreaRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRP.ProtoReflect.Descriptor instead.
func (*AreaRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *AreaRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AreaRP) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *AreaRP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EquipmentRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	HomeId        int32                  `protobuf:"varint,3,opt,name=homeId,proto3" json:"homeId,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TimeStart     string                 `protobuf:"bytes,6,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,7,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	TurnOn        bool                   `protobuf:"varint,8,opt,name=turnOn,proto3" json:"turnOn,omitempty"`
	Cycle         int32                  `protobuf:"varint,9,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRP) Reset() {
	*x = EquipmentRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRP) ProtoMessage() {}

func (x *EquipmentRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRP.ProtoReflect.Descriptor instead.
func (*EquipmentRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentRP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentRP) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *EquipmentRP) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

func (x *EquipmentRP) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EquipmentRP) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EquipmentRP) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *EquipmentRP) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *EquipmentRP) GetTurnOn() bool {
	if x != nil {
		return x.TurnOn
	}
	return false
}

func (x *EquipmentRP) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *EquipmentRP) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EquipmentRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRQ) Reset() {
	*x = EquipmentRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRQ) ProtoMessage() {}

func (x *EquipmentRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRQ.ProtoReflect.Descriptor instead.
func (*EquipmentRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *EquipmentRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

type HomeRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRQ) Reset() {
	*x = HomeRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRQ) ProtoMessage() {}

func (x *HomeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRQ.ProtoReflect.Descriptor instead.
func (*HomeRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{4}
}

func (x *HomeRQ) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type AreaRQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        int32                  `protobuf:"varint,1,opt,name=homeId,proto3" json:"homeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRQ) Reset() {
	*x = AreaRQ{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRQ) ProtoMessage() {}

func (x *AreaRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRQ.ProtoReflect.Descriptor instead.
func (*AreaRQ) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{5}
}

func (x *AreaRQ) GetHomeId() int32 {
	if x != nil {
		return x.HomeId
	}
	return 0
}

type ListHomeRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Homes         []*HomeRP              `protobuf:"bytes,1,rep,name=homes,proto3" json:"homes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHomeRP) Reset() {
	*x = ListHomeRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHomeRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeRP) ProtoMessage() {}

func (x *ListHomeRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeRP.ProtoReflect.Descriptor instead.
func (*ListHomeRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{6}
}

func (x *ListHomeRP) GetHomes() []*HomeRP {
	if x != nil {
		return x.Homes
	}
	return nil
}

type ListAreaRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*AreaRP              `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreaRP) Reset() {
	*x = ListAreaRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreaRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaRP) ProtoMessage() {}

func (x *ListAreaRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaRP.ProtoReflect.Descriptor instead.
func (*ListAreaRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{7}
}

func (x *ListAreaRP) GetAreas() []*AreaRP {
	if x != nil {
		return x.Areas
	}
	return nil
}

type ListEquimentRP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equipments    []*EquipmentRP         `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEquimentRP) Reset() {
	*x = ListEquimentRP{}
	mi := &file_proto_equipment_equipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEquimentRP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEquimentRP) ProtoMessage() {}

func (x *ListEquimentRP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_equipment_equipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEquimentRP.ProtoReflect.Descriptor instead.
func (*ListEquimentRP) Descriptor() ([]byte, []int) {
	return file_proto_equipment_equipment_proto_rawDescGZIP(), []int{8}
}

func (x *ListEquimentRP) GetEquipments() []*EquipmentRP {
	if x != nil {
		return x.Equipments
	}
	return nil
}

var File_proto_equipment_equipment_proto protoreflect.FileDescriptor

var file_proto_equipment_equipment_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x86, 0x01, 0x0a,
	0x06, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x44, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61, 0x52, 0x50, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8b, 0x02, 0x0a, 0x0b,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x45, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x79, 0x63, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x51, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64,
	0x22, 0x26, 0x0a, 0x06, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x51, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x51, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0a, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x12, 0x27, 0x0a, 0x05, 0x68, 0x6f, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x52, 0x05, 0x68, 0x6f, 0x6d, 0x65,
	0x73, 0x22, 0x35, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x50, 0x12,
	0x27, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x50, 0x52, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x22, 0x48, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x71, 0x75, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x12, 0x36, 0x0a, 0x0a, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x32, 0xbc, 0x01, 0x0a, 0x10, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x12,
	0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x6f, 0x6d, 0x65,
	0x52, 0x51, 0x1a, 0x15, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x50, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x04, 0x41,
	0x72, 0x65, 0x61, 0x12, 0x11, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x51, 0x1a, 0x15, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x50, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x51, 0x1a, 0x19, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x71, 0x75, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x50, 0x22,
	0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_equipment_equipment_proto_rawDescOnce sync.Once
	file_proto_equipment_equipment_proto_rawDescData []byte
)

func file_proto_equipment_equipment_proto_rawDescGZIP() []byte {
	file_proto_equipment_equipment_proto_rawDescOnce.Do(func() {
		file_proto_equipment_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_equipment_equipment_proto_rawDesc), len(file_proto_equipment_equipment_proto_rawDesc)))
	})
	return file_proto_equipment_equipment_proto_rawDescData
}

var file_proto_equipment_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_equipment_equipment_proto_goTypes = []any{
	(*HomeRP)(nil),         // 0: equipment.HomeRP
	(*AreaRP)(nil),         // 1: equipment.AreaRP
	(*EquipmentRP)(nil),    // 2: equipment.EquipmentRP
	(*EquipmentRQ)(nil),    // 3: equipment.EquipmentRQ
	(*HomeRQ)(nil),         // 4: equipment.HomeRQ
	(*AreaRQ)(nil),         // 5: equipment.AreaRQ
	(*ListHomeRP)(nil),     // 6: equipment.ListHomeRP
	(*ListAreaRP)(nil),     // 7: equipment.ListAreaRP
	(*ListEquimentRP)(nil), // 8: equipment.ListEquimentRP
}
var file_proto_equipment_equipment_proto_depIdxs = []int32{
	0, // 0: equipment.ListHomeRP.homes:type_name -> equipment.HomeRP
	1, // 1: equipment.ListAreaRP.areas:type_name -> equipment.AreaRP
	2, // 2: equipment.ListEquimentRP.equipments:type_name -> equipment.EquipmentRP
	4, // 3: equipment.EquipmentService.Home:input_type -> equipment.HomeRQ
	5, // 4: equipment.EquipmentService.Area:input_type -> equipment.AreaRQ
	3, // 5: equipment.EquipmentService.Equipment:input_type -> equipment.EquipmentRQ
	6, // 6: equipment.EquipmentService.Home:output_type -> equipment.ListHomeRP
	7, // 7: equipment.EquipmentService.Area:output_type -> equipment.ListAreaRP
	8, // 8: equipment.EquipmentService.Equipment:output_type -> equipment.ListEquimentRP
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_equipment_equipment_proto_init() }
func file_proto_equipment_equipment_proto_init() {
	if File_proto_equipment_equipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_equipment_equipment_proto_rawDesc), len(file_proto_equipment_equipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_equipment_equipment_proto_goTypes,
		DependencyIndexes: file_proto_equipment_equipment_proto_depIdxs,
		MessageInfos:      file_proto_equipment_equipment_proto_msgTypes,
	}.Build()
	File_proto_equipment_equipment_proto = out.File
	file_proto_equipment_equipment_proto_goTypes = nil
	file_proto_equipment_equipment_proto_depIdxs = nil
}
