// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID       *int    `json:"id,omitempty"`
	FullName *string `json:"fullName,omitempty"`
	Email    *string `json:"email,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Token    *string `json:"token,omitempty"`
}

type LoginAccount struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterAccount struct {
	FullName string  `json:"fullName"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Phone    string  `json:"phone"`
	Otp      *string `json:"otp,omitempty"`
}

type TokenAccount struct {
	Token string `json:"token"`
}
