package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"ThaiLy/graph/generated"
	"ThaiLy/graph/model"
	"context"
)

// Equipment is the resolver for the equipment field.
func (r *areaResolver) Equipment(ctx context.Context, obj *model.Area) ([]*model.Equipment, error) {
	return r.Ctrl.GetEquipment(obj)
}

// Area is the resolver for the area field.
func (r *homeResolver) Area(ctx context.Context, obj *model.Home) ([]*model.Area, error) {
	return r.Ctrl.GetArea(obj)
}

// Area returns generated.AreaResolver implementation.
func (r *Resolver) Area() generated.AreaResolver { return &areaResolver{r} }

// Home returns generated.HomeResolver implementation.
func (r *Resolver) Home() generated.HomeResolver { return &homeResolver{r} }

type areaResolver struct{ *Resolver }
type homeResolver struct{ *Resolver }
