package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"ThaiLy/graph/generated"
	"ThaiLy/graph/model"
	"context"
)

// Equipment is the resolver for the equipment field.
func (r *areaQueryResolver) Equipment(ctx context.Context, obj *model.AreaQuery) ([]*model.Equipment, error) {
	return r.Equipment(ctx, obj)
}

// Area is the resolver for the area field.
func (r *homeQueryResolver) Area(ctx context.Context, obj *model.HomeQuery) ([]*model.AreaQuery, error) {
	return r.Area(ctx, obj)
}

// AreaQuery returns generated.AreaQueryResolver implementation.
func (r *Resolver) AreaQuery() generated.AreaQueryResolver { return &areaQueryResolver{r} }

// HomeQuery returns generated.HomeQueryResolver implementation.
func (r *Resolver) HomeQuery() generated.HomeQueryResolver { return &homeQueryResolver{r} }

type areaQueryResolver struct{ *Resolver }
type homeQueryResolver struct{ *Resolver }
