package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"ThaiLy/graph/generated"
	"ThaiLy/graph/model"
	"context"
)

// DeviceStatusUpdated is the resolver for the deviceStatusUpdated field.
func (r *subscriptionResolver) DeviceStatusUpdated(ctx context.Context) (<-chan *model.Device, error) {
	return r.Ctrl.DeviceStatusUpdated(ctx)
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
