services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"  # MQTT protocol
      - "9001:9001"  # WebSocket (nếu cần)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Cấu hình listener
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Fix lỗi __consumer_offsets
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka


  server:
    image: thaily/server
    env_file: 
      - .server.env
    depends_on:
      - kafka
    networks:
      - app-network
    ports:
      - "8081:8081"
  server-mqtt:
    image: thaily/mqtt
    env_file:
      - .mqtt.env
    depends_on:
      - kafka
    networks:
      - app-network
    ports:
      - "5000:5000"

  service-auth:
    image: thaily/service-auth
    env_file: 
      - .service.auth.env
    networks:
      - app-network
    ports:
      - "55555:55555"

  service-equipment:
    image: thaily/service-equipment
    env_file: 
      - .service.equipment.env
    networks:
      - app-network
    ports:
      - "55556:55556"

  service-kafka:
    image: thaily/service-kafka
    env_file: 
      - .service.kafka.env
    networks:
      - app-network
    ports:
      - "55557:55557"

networks:
  app-network:
    driver: bridge
